silent: false

tasks:
  release:
    desc: Release a new version of IBEXUS Connector
    cmds:
      - |
        # Get the new version tag
        NEW_VERSION=$(echo <.version)

        # Check if there are uncommitted changes and commit them if any
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Release ${NEW_VERSION:1}"
        fi

        # Add a tag to the latest commit with the new version number
        git tag $NEW_VERSION

        # Push changes and tags to the origin
        git push origin main
        git push origin $NEW_VERSION
set: [e, u, pipefail]
version: 3
