silent: false

tasks:
  release:
    desc: Release a new version of IBEXUS Connector
    cmds:
      - |
        # start colima if not running
        colima status >/dev/null 2>&1 || colima start --cpu 12 --memory 32 --disk 100 --vm-type=vz --vz-rosetta

        # Get the new version tag
        NEW_VERSION=$(cat .version)

        # Check if there are uncommitted changes and commit them if any
        if [[ -n $(git status -s) ]]; then
          git add .
          git commit -m "Release ${NEW_VERSION:1}"
        fi

        # Add a tag to the latest commit with the new version number
        if git rev-parse "${NEW_VERSION}" >/dev/null 2>&1; then
            echo "Tag ${NEW_VERSION} exists already, deleting"
            git tag -d $NEW_VERSION
            git push --delete origin $NEW_VERSION
        fi
        git tag $NEW_VERSION

        # Push changes and tags to the origin
        git push origin main
        git push origin $NEW_VERSION

        # Publish to Docker Hub
        docker logout
        echo $(op read "op://IBEXUS/Docker Hub/personal access token") | docker login -u ibexus --password-stdin
        # scripts/dockerhub-publish.sh -f assets/ibexus-connector-image-${NEW_VERSION:1}.tar -r ibexus-platform/ibexus-connector -t ${NEW_VERSION} --also-latest
set: [e, u, pipefail]
version: 3
