name: create release, add assets and publish to docker hub

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Get release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        # use as ${VERSION}

    - name: Create a Release
      id: create_release
      uses: shogo82148/actions-create-release@v1

    - name: Upload Assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/assets/ibexus-connector-${VERSION}-x86_64-linux.zip

    # - name: docker login
    #   env:
    #     DOCKER_USER: "ibexus"
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    #   run: |
    #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    # - name: Load the Docker image
    #   run: docker load < 
    # - name: Docker Push
    #   run: docker push chamodshehanka/node-test

# name: Deploy README to Docker Hub repository description
# on:
#   push:
#     branches: [ "main" ]
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       - name: Docker Hub Description
#         uses: peter-evans/dockerhub-description@v3
#         with:
#           username: ibexus
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#           repository: ibexus/ibexus-connector
        
      # # Runs a set of commands using the runners shell
      # - name: Deploy README.md as repository full_description on Docker Hub
      #   run: |
      #     echo test
      #     USERNAME="ibexus"
      #     PASSWORD=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #     REPO_USER="ibexus"
      #     REPO_NAME="ibexus-connector"
      #     DESCRIPTION="test \n test <br> **test** \\n *test*"
      #     API_URL="https://hub.docker.com/v2"
      #     TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$USERNAME'", "password": "'$PASSWORD'"}' $API_URL/users/login/ | jq -r .token)
      #     curl -s -H "Authorization: JWT $TOKEN" -H "Content-Type: application/json" -X PATCH -d '{"full_description": "'$DESCRIPTION'"}' $API_URL/repositories/$REPO_USER/$REPO_NAME/
