name: Create and distribute release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Get release version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo Version: $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        # use as ${VERSION}

    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: assets/ibexus-connector-*.zip
        artifactContentType: application/zip
        makeLatest: true   
        tag: v0.1.1

    # - name: Create a Release
    #   id: create_release
    #   uses: shogo82148/actions-create-release@v1

    # - name: Upload Assets
    #   uses: shogo82148/actions-upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: assets/ibexus-connector-*.zip
    #     overwrite: true

    - name: Push image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u "ibexus" --password-stdin
        docker load < ${{ github.workspace }}/assets/ibexus-connector-image-${VERSION}.tar
        docker push ibexus/ibexus-connector
