name: Deploy README to Docker Hub repository description
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Deploy README.md as repository full_description on Docker Hub
        run: |
          echo test
          # USERNAME="ibexus"
          # PASSWORD=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          # REPO_USER="ibexus"
          # REPO_NAME="ibexus-connector"
          # DESCRIPTION=$(cat $GITHUB_WORKSPACE/README.md)
          # API_URL="https://hub.docker.com/v2"
          # TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$USERNAME'", "password": "'$PASSWORD'"}' $API_URL/users/login/ | jq -r .token)
          # curl -s -H "Authorization: JWT $TOKEN" -H "Content-Type: application/json" -X PATCH -d '{"full_description": "'$DESCRIPTION'"}' $API_URL/repositories/$REPO_USER/$REPO_NAME/
